#!/usr/bin/env python
"""Fuzzing harness for input validation.

This fuzzer tests the input validation functions for edge cases and
potential vulnerabilities using Atheris fuzzing framework.

Targets:
- Input validation
- Type checking
- Boundary conditions
- Error handling

Usage:
    python fuzz/fuzz_input_validation.py -max_total_time=60
"""

import sys

import atheris

with atheris.instrument_imports():
    from {{cookiecutter.project_slug}} import validate_input


def TestOneInput(data: bytes) -> None:
    """Fuzz test input validation with arbitrary byte sequences.

    This function is called by Atheris with random byte sequences to discover
    edge cases, crashes, and unexpected behaviors in input validation.

    Args:
        data: Random byte sequence generated by the fuzzer.

    Edge cases tested:
    - Empty inputs
    - Very large inputs
    - Invalid UTF-8 sequences
    - Special characters
    - Null bytes
    - Format string patterns
    """
    # Skip inputs that are too small
    if len(data) < 1:
        return

    try:
        # Test string conversion and validation
        validate_input(data.decode("utf-8", errors="ignore"))
    except ValueError:
        # Expected for invalid inputs
        pass
    except UnicodeDecodeError:
        # Expected for invalid UTF-8
        pass
    except Exception:
        # Fuzzer should not crash on invalid input
        # All exceptions are expected and should be handled gracefully
        pass


def main() -> None:
    """Initialize and run the fuzzer."""
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
